In [1]:
from Detector import *

In [2]:
modelURL="http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz"

#modelURL="http://download.tensorflow.org/models/object_detection/tf2/20200711/efficientdet_d4_coco17_tpu-32.tar.gz"

In [3]:
#modelURL="http://download.tensorflow.org/models/object_detection/tf2/20200711/faster_rcnn_resnet50_v1_640x640_coco17_tpu-8.tar.gz"

In [4]:
classFile="coco.names"
detector=Detector()
detector.readClasses(classFile)
detector.downloadModel(modelURL)
detector.loadModel()

Loading Model ssd_mobilenet_v2_320x320_coco17_tpu-8


InternalError: cudaGetDevice() failed. Status: initialization error

In [ ]:
threshold=0.5
imagePath="1.jpg"           
detector.predictImage(imagePath,threshold)

In [ ]:
imagePath="2.jpg"           
detector.predictImage(imagePath,threshold)

In [12]:
videoPath="sample.mp4"
detector.predictVideo(videoPath,threshold)

tf.Tensor([0 1 2 3 4 5 6 7 9], shape=(9,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 9], shape=(7,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 8 9], shape=(9,), dtype=int32)
tf.Tensor([0 1 2 3 4 6], shape=(6,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 7 8], shape=(8,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 9], shape=(9,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8 10], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7 10 11], shape=(10,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  7  8  9 10 11 12 13], shape=(13,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  7  8  9 10 11 12], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  9 10 11], shape=(11,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  8  9 10 11 12 14], shape=(13,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5 

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12], shape=(13,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12], shape=(13,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12], shape=(13,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  6  7  8  9 10 11], shape=(11,), dtype=int32)
